backend:
  name: github
  repo: TU_USUARIO/mi-portafolio
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "config" 
    label: "Configuración"
    files:
      - file: "data/config.yml"
        label: "Datos principales"
        name: "config"
        fields:
          - {label: "Nombre", name: "nombre", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "LinkedIn", name: "linkedin", widget: "string"}
          - {label: "GitHub", name: "github", widget: "string"}

  - name: "proyectos"
    label: "Proyectos"
    folder: "data/proyectos"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "titulo", widget: "string"}
      - {label: "Descripción", name: "descripcion", widget: "text"}
      - {label: "Enlace", name: "enlace", widget: "string"}
      - {label: "Imagen", name: "imagen", widget: "image"}

  - name: "certificados"
    label: "Certificados"
    folder: "data/certificados"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre", name: "nombre", widget: "string"}
      - {label: "Enlace", name: "enlace", widget: "string"}
